@BASE_URL = {{$dotenv BASE_URL}}

### /users
GET {{BASE_URL}}/users
Content-Type: application/json
###
POST {{BASE_URL}}/users
Content-Type: application/json

{"username":"Jeana","password":"password", "email":"jean@gmail.com"}
###
GET {{BASE_URL}}/users/dfe899b3-7232-4508-a18d-695eb40e5e59
Content-Type: application/json
###
PUT {{BASE_URL}}/users/dfe899b3-7232-4508-a18d-695eb40e5e59
Content-Type: application/json

{"phoneNumber":"0789277275", "name":"Luc Abayo"}

###

PUT {{BASE_URL}}/users/dfe899b3-7232-4508-a18d-695eb40e5e59/passwords
Content-Type: application/json

{"password":"passwordkjhkaf"}
